### ISSUE TITLE
random_brightness shifts the image normalization

### ISSUE THREAD

**Issue by guhur** [keras-team/keras-preprocessing#114]
My images are trained with float representation, so that their maximum value is 1.0.
However, when I applied `random_brightness`, the image is between 0.0 and 255.0

I think this is not expected, or at least, it should be warned in the documentation, shouldn't it?

**Comment by fabiomaia** [comment]
I faced the same issue I think. However I had a bunch of transformations declared so I didn't pinpoint which one was actually responsible.

I also didn't expect it and I didn't see anything about it in the documentation, but I just slapped `rescale=1./255` and moved on after having wasted so much time fiddling with it.

**Comment by plguhur** [comment]
Well actually the values are not actually between 0.0 and 255.0 but between 0.0 and a value related to the brightness value.

In the end, I avoided the problem with:

```
max_x = np.max(x)
x = random_brightness(x, transform_parameters.get('brightness'))
x /= max_x
```

I guess it would make sense to include it inside `apply_brightness_shift`. I can make a PR if you agree with it.

**Comment by qinst64** [comment]
I believe this is a bug,  `brightness_range`  will cause the image rescale to range 0-255.
The `scale` parameter is not set while calling `array_to_img` however the default is True.

Check [here](https://github.com/keras-team/keras/issues/10366#issuecomment-496230126) and [the explanation](https://github.com/keras-team/keras/issues/10366#issuecomment-511316954).


To fix, change to code as commented:
```python
def apply_brightness_shift(x, brightness):
    #...
    x = array_to_img(x) # change to x = array_to_img(x, rescale=False)
    x = imgenhancer_Brightness = ImageEnhance.Brightness(x)
    x = imgenhancer_Brightness.enhance(brightness)
    x = img_to_array(x)
    return x
```
