### ISSUE TITLE
Pillow dependency

### ISSUE THREAD

**Issue by fabiomaia** [keras-team/keras-preprocessing#115]
In https://github.com/keras-team/keras-preprocessing/blob/master/setup.py

```python
extras_require={
    'tests': ['pytest',
        'pytest-pep8',
        'pytest-xdist',
        'pytest-cov'],
    'image': ['scipy>=0.14'],
},
```

Shouldn't `Pillow` also be declared?

I just did a fresh virtual env install and after `pip install -r requirements.txt` (which doesn't contain `Pillow` because I assume you take care of that) I noticed that my code fails because `Pillow` isn't installed.

**Comment by Dref360** [comment]
Pillow is not a dependency because you should be able to use keras-preprocessing on text without this package.

**Comment by Dref360** [comment]
Fix by https://github.com/keras-team/keras-preprocessing/pull/117
