### ISSUE TITLE
ImageDataGenerator breaks when used with a validation_split and no labels 

### ISSUE THREAD

**Issue by chrisdahlberg** [keras-team/keras-preprocessing#129]
The check for the number of labels after applying the validation split in numpy_array_iterator.py is missing a check for if there are no labels (y is None).  It tries to count the number of classes in the non-existent y post split.

**Comment by rragundez** [comment]
Thanks for submitting the issue @chrisdahlberg , PR #133 addresses the problem.

**Comment by rragundez** [comment]
@Dref360 this Issue should be closed, It was resolve by PR #133
