### ISSUE TITLE
Documentation for text.Tokenizer not rendering correctly in the browser

### ISSUE THREAD

**Issue by adammarples** [keras-team/keras-preprocessing#146]
The documentation for Tokenizer class constructor kwarg is rendering incorrectly in the browser.

filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~\t\n'

But in the browser it renders an actual tab and newline

filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~  
'

See: https://keras.io/preprocessing/text/

**Comment by qwertpi** [comment]
> The documentation for Tokenizer class constructor kwarg is rendering incorrectly in the browser.
> 
> filters='!"#$%&()*+,-./:;<=>?@[]^_`{|}~\t\n'
> 
> But in the browser it renders an actual tab and newline
> 
> filters='!"#$%&()*+,-./:;<=>?@[]^_`{|}~
> '
> 
> See: https://keras.io/preprocessing/text/

I don't see this in chrome 77

**Comment by Dref360** [comment]
This is fixed I think.
