### ISSUE TITLE
Provide Sample Weights to ImageDataGenerator.flow_from_dataframe

### ISSUE THREAD

**Issue by docmarionum1** [keras-team/keras-preprocessing#147]
I'd like to specify sample weights when using `ImageDataGenerator.flow_from_dataframe`. I see that `flow` supports it, so I could load my images into a numpy array first and use flow. But it seems like it makes sense to allow `flow_from_dataframe` to support it as well.

To implement, `flow_from_dataframe` would optionally take a `weight_col` parameter, and then if `weight_col` is not None, `_get_batches_of_transformed_samples` would return a third item,  the sample weights.

I'd be happy to send a pull request if this is something that y'all agree makes sense.

**Comment by rragundez** [comment]
I was thinking on adding that so this would be a great addition. Please name the column accordingly to the parameter in flow. I think `sample_weights_col`.

**Comment by rragundez** [comment]
@docmarionum1 I created PR #166 that implements this. Please have a look.

**Comment by docmarionum1** [comment]
@rragundez Thanks! Testing it out and it works great!

**Comment by lluissalord** [comment]
Could it be the case that for multi-output it is not working? Because I tried to pass a list or a dictionary to weight_col and it gave me the following error:

> /opt/conda/lib/python3.6/site-packages/keras_preprocessing/image/image_data_generator.py in flow_from_dataframe(self, dataframe, directory, x_col, y_col, weight_col, target_size, color_mode, classes, class_mode, batch_size, shuffle, seed, save_to_dir, save_prefix, save_format, subset, interpolation, validate_filenames, **kwargs)
>     681             subset=subset,
>     682             interpolation=interpolation,
> --> 683             validate_filenames=validate_filenames
>     684         )
>     685 
> 
> /opt/conda/lib/python3.6/site-packages/keras_preprocessing/image/dataframe_iterator.py in __init__(self, dataframe, directory, image_data_generator, x_col, y_col, weight_col, target_size, color_mode, classes, class_mode, batch_size, shuffle, seed, data_format, save_to_dir, save_prefix, save_format, subset, interpolation, dtype, validate_filenames)
>     127         self.dtype = dtype
>     128         # check that inputs match the required class_mode
> --> 129         self._check_params(df, x_col, y_col, weight_col, classes)
>     130         if validate_filenames:  # check which image files are valid and keep them
>     131             df = self._filter_valid_filepaths(df, x_col)
> 
> /opt/conda/lib/python3.6/site-packages/keras_preprocessing/image/dataframe_iterator.py in _check_params(self, df, x_col, y_col, weight_col, classes)
>     211                           .format(self.class_mode))
>     212         # check that if weight column that the values are numerical
> --> 213         if weight_col and not issubclass(df[weight_col].dtype.type, np.number):
>     214             raise TypeError('Column weight_col={} must be numeric.'
>     215                             .format(weight_col))
> 
> /opt/conda/lib/python3.6/site-packages/pandas/core/generic.py in __getattr__(self, name)
>    5177             if self._info_axis._can_hold_identifiers_and_holds_name(name):
>    5178                 return self[name]
> -> 5179             return object.__getattribute__(self, name)
>    5180 
>    5181     def __setattr__(self, name, value):
> 
> AttributeError: 'DataFrame' object has no attribute 'dtype'

**Comment by rragundez** [comment]
@lluissalord the weights are per observation. So I don't know what you mean, even if you have a multi-output network, suppose 5 different outputs, each 5 outputs belong to a single observation.

**Comment by lluissalord** [comment]
If I use one column for `weight_col = 'sample_weights'`  with a training DataFrame as:

![imagen](https://user-images.githubusercontent.com/7021552/67295453-6b84d180-f4e7-11e9-8925-9c1370388d3d.png)

And definin `flow_from_dataframe `as below:

```
train_generator = datagen.flow_from_dataframe(train_df, 
                                              directory=TRAIN_PNG, 
                                              x_col='filename', 
                                              y_col=CLASSES, 
                                              weight_col='sample_weights',
                                              target_size=img_size, 
                                              color_mode='rgb', 
                                              #class_mode='other', 
                                              class_mode='multi_output', 
                                              batch_size=BATCH_SIZE, 
                                              shuffle=True, 
                                              seed=SEED, 
                                              save_to_dir=AUG_TRAIN_PNG, save_prefix='aug_',
                                              interpolation='bilinear')
```

I get this error when trying to train:

> /opt/conda/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
>    1431         shuffle=shuffle,
>    1432         initial_epoch=initial_epoch,
> -> 1433         steps_name='steps_per_epoch')
>    1434 
>    1435   def evaluate_generator(self,
> 
> /opt/conda/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py in model_iteration(model, data, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch, mode, batch_size, steps_name, **kwargs)
>     262 
>     263       is_deferred = not model._is_compiled
> --> 264       batch_outs = batch_function(*batch_data)
>     265       if not isinstance(batch_outs, list):
>     266         batch_outs = [batch_outs]
> 
> /opt/conda/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py in train_on_batch(self, x, y, sample_weight, class_weight, reset_metrics)
>    1151     x, y, sample_weights = self._standardize_user_data(
>    1152         x, y, sample_weight=sample_weight, class_weight=class_weight,
> -> 1153         extract_tensors_from_dataset=True)
>    1154 
>    1155     # If `self._distribution_strategy` is True, then we are in a replica context
> 
> /opt/conda/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, batch_size, check_steps, steps_name, steps, validation_split, shuffle, extract_tensors_from_dataset)
>    2676       # `class_weight` arguments.
>    2677       sample_weights = training_utils.standardize_sample_weights(
> -> 2678           sample_weight, feed_output_names)
>    2679       class_weights = training_utils.standardize_class_weights(
>    2680           class_weight, feed_output_names)
> 
> /opt/conda/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_utils.py in standardize_sample_weights(sample_weight, output_names)
>     439 def standardize_sample_weights(sample_weight, output_names):
>     440   return standardize_sample_or_class_weights(sample_weight, output_names,
> --> 441                                              'sample_weight')
>     442 
>     443 
> 
> /opt/conda/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_utils.py in standardize_sample_or_class_weights(x_weight, output_names, weight_type)
>     429                     'should be either a list or a dict. '
>     430                     'Provided `' + weight_type + '` type not understood: ' +
> --> 431                     str(x_weight))
>     432 
>     433 
> 
> TypeError: The model has multiple outputs, so `sample_weight` should be either a list or a dict. Provided `sample_weight` type not understood: 

Hence, I am doing something wrong or it is not clear what to use in case of multi-output.

Thanks!

**Comment by rragundez** [comment]
@lluissalord thanks for clarifying, it indeed seems like a bug. Can you open a separate issue for it? make sure there is a minimal reproducible example. This means anyone by running the piece of code you provide can find the same issue.
