### ISSUE TITLE
array_to_image errors

### ISSUE THREAD

**Issue by surgan12** [keras-team/keras-preprocessing#148]
When we convert Image in mode 'L' to a numpy array it has dimensions 2 .
Using array_to_image to convert back it to Image , it gives error .

**Comment by rragundez** [comment]
The docstring of the function is pretty clear on what is expecting. and it requires a small change in the users side. Can you elaborate on why is that not enough?

https://github.com/keras-team/keras-preprocessing/blob/db7e3d92200c11924a6a4f9049f4dd734518f4b6/keras_preprocessing/image/utils.py#L210
