### ISSUE TITLE
datagen.flow_from_dataframe erro after update 

### ISSUE THREAD

**Issue by khaledbnmohamed** [keras-team/keras-preprocessing#152]
An Error just popped-up tonight after the last update today

for a line ```

```
 train_generator=datagen.flow_from_dataframe(dataframe=df_train, directory=None,x_col="Img_Path",
                                              y_col="Label", class_mode="binary", target_size=(224,224), batch_size=batch)
```

Error :
TypeError: If class_mode="binary", y_col="Label" column values must be strings.

the code was working fine just before the last Keras commit as I'm using the latest version

**Comment by rojinsafavi** [comment]
I'm having the same problem, and my column labels are strings

**Comment by rojinsafavi** [comment]
I think it won't make sense to convert the whole data frame to string. What if one of the columns is the binary label?

**Comment by rragundez** [comment]
oh sorry @rojinsafavi , I updated the answer Indeed you only want to  change the the string column by `df['coluumn_name'].astype('str')`.

I'm also interested in you comment 
> I'm having the same problem, and my column labels are strings
This is very strange, do you have a minimal repproducible example?

**Comment by rojinsafavi** [comment]
It is weird, because I do not get any error when I use the jupyter notebook, but I do get an error when I use the terminal to run my code (python code.py). I also double checked the keras version and it is 2.2.4 in the terminal and jupyter notebook. My dataframe has two labels, one is the image name and the other one is the label. The columns are all string ( name, label). I'll try to upload an example soon

**Comment by rojinsafavi** [comment]
Are you suggesting that the values within the label column should be string instead of being binary? [0,1]

**Comment by rojinsafavi** [comment]
this is how the table looks like

[                                              id  label
135159  c992184aa14f9f5a229b1a9d32baab139eeb3a01      0
14122   fb2718e959883b55b98b3e2657855bc5837f8d75      1
90607   948f48049b541ebae82965ecf01c6b8efaddaa49      1
91534   857ea0ebbadbcbd21744166e5adf322f79387f9e      0
218175  fd96c193722d0ada23d447a0fa45cc58e40e2188      1
73548   da774268e11eb67c85703196c91b0235e09184fd      0
156394  a26dbbda1008e9990debae11961f7d1650ecde88      0
124165  56f3067f8cd52fcf789c8b64b80cfdabe49c39cf      1
148721  03a12ee23f9cb5f8d252423be37227fa9adf24e6      1
9158    059c55a8757b4af90f389ade6409a0c596943073      1
193103  9cee1dbd39d0e3f4472e6bb2b3b313e95c14f52c      0
123338  b149890f0ec9f9e242add1d8f94bc871b8d74298      0
41873   14966197db2f666af8ef7896831a24a4724d8283      1
166253  9c9bbaf89cb0a371c1e1a75bc22003538bbdd5b6      1
66862   13550a3a05395d289ca5281ff9adf51b35118b17      0
105770  767bbe1d4972e22542721da9c694eb4d748724fa      0
14206   971ebdaeef321767abaf9a82e323000629095301      1](url)

**Comment by alkra1** [comment]
thanks. but this never used to be a problem... ive been running it for weeks. and why does binary require string? 

and then i changed to string:
df['R_eye'] = df['R_eye'].apply(str)
is_string_dtype(df['R_eye'])
True

and got same error

TypeError: If class_mode="binary", y_col="R_eye" column values must be strings.

**Comment by rragundez** [comment]
> oh sorry @rojinsafavi , I updated the answer Indeed if you only want to change a single column then `df['coluumn_name'] = df['coluumn_name'].astype(str)`. But I'm open to hear use cases where doing the casting to string is not sufficient. Perhaps a small explanation from my side, what I want to do with this is that there is a clear distinction between class labels and class indices, to avoid confusion down the line, for example, you could throw the integer labels 23, 0, 21, 2 but then the batches are created the position is actually the indices 3, 0, 2, 1 of those labels, so when experimenting/reviewing/debugging the batches, the user might indeed use the class labels and get a wrong result even though it might work (not raise an error), there was an issue like that where that was the culprit if I remember correctly and I'v seen it happen as well. Plus avoiding a mix of string and integers as labels. Plus keeping a consistent input type which is normally a good idea. But like I said I'm open to hear counterarguments or specially use cases where the current implementationn is not sufficient.
> 
> I'm also interested in you comment
> 
> > I'm having the same problem, and my column labels are strings
> 
> This is very strange, do you have a minimal reproducible example?

Does the above explanation help? It has to do with the concept of the `y_col` which should include labels, and at the moment `binary` also does the same logic than `sparse` with 2 labels. So you can run binary with any two labels actually. Then you have the problem I mention above. I would actually suggest the `binary` method should since  `sparse` already does the same thing.

**Comment by alkra1** [comment]
has something changed though? 
i am familiar with y_col, which when used with 'binary' has always run when my y_col data was an integer.
now, i got a new error, and changed the y_col data type to a string with binary and its still not running.
could you please advise recommended combination of class_mode and data type?

**Comment by rragundez** [comment]
Yes the code change to satisfy the points I made above, which has todo with the addition of new use cases.

 Strings with binary should be OK, can you send a minimal reproducible example?

**Comment by alkra1** [comment]
df['R_eye'] = df['R_eye'].apply(str)
is_string_dtype(df['R_eye'])
df['R_eye'].head()
0    0
1    1
2    0
3    1
4    0
Name: R_eye, dtype: object

**Comment by rragundez** [comment]
Hi @Atralb, what you suggest is not a good practice, and I believe the points I made are still relevant. In essence it boils down to the concept that labels, and classes should be strings as defining an adjective/subject/characteristic to an image. 
If you already did the preprocessing to extract label indices and want to use them as is, then you don't need the classes to indices logic, you can just use the `raw` mode.
I hope this helps clear things out.

**Comment by samuruga** [comment]
Hello All,

Has this issue been resolved? If so can I please know the correct solution?
