### ISSUE TITLE
Add pandas as a dependency

### ISSUE THREAD

**Issue by paulgc** [keras-team/keras-preprocessing#154]
Import fails when pandas is not already installed.

`from keras_preprocessing import image`

results in

`ImportError: No module named pandas.api.types`

pandas should be specified as a dependency in setup.py

**Comment by ravelab** [comment]
saw this error too, tensorflow in one of my docker containers failed, and I won't be able to add pandas as dependency easily

**Comment by yangsiran** [comment]
Similar problem was met when installing and running tensorflow with keras-preprocessing 1.0.6

**Comment by rragundez** [comment]
Hi thanks very much for pointing it out, actually the import seems to be unused, so it should just be removed.

https://github.com/keras-team/keras-preprocessing/blob/281090d8ab7bdfa47408624c31fad9481db51227/keras_preprocessing/image/dataframe_iterator.py#L11

**Comment by nhc-motosumo** [comment]
This (very temporary!) workaround worked for me: Force old version before installing the package that requires _keras_:
`pip3 install Keras-Preprocessing==1.0.5`

**Comment by DavidNorman** [comment]
actually the above issue isn't exactly the same.  but there is an issue with installing and running TF at the moment due to this missing dependency.

Is there an ETA for a fix?

**Comment by rragundez** [comment]
It has been merged to master. Waiting on feedback about a minor release.

**Comment by kokes** [comment]
@rragundez thanks for the fix! Have you pushed it to pypi? It's still [not showing up](https://pypi.org/project/Keras-Preprocessing/#history), not sure if there's an approval process or something.

**Comment by Dref360** [comment]
@fchollet could you push the new version please? 

We are working on a test that would catch this kind of issue. Sorry for the inconvenience.

**Comment by Dref360** [comment]
Update: There is a new version (1.0.8) on pip.
