### ISSUE TITLE
Flow from dataframe to support 4 color channels

### ISSUE THREAD

**Issue by cameronbronstein** [keras-team/keras-preprocessing#165]
Hi there.

I am using the `.flow_from_dataframe` for the newest ImageDataGenerator for a multi-label classification problem. It has been amazing for me, but I wanted to bring up the issue that this method currently only support 1 or 3 color channels. My project is with Satellite Imagery, which commonly has Near IR bands. It would be great to be able to use all the bands. 

I believe similar [issues](https://github.com/keras-team/keras/issues/4664) have reported prior to the .flow_from_dataframe method, and were update accordingly for `.flow` and `.flow_from_directory`.

```
color_mode: one of "grayscale", "rbg". Default: "rgb".
            Whether the images will be converted to have
            1 or 3 color channels.
```

Thank you thank you!

**Comment by Dref360** [comment]
I think this is just misleading doc from `flow_from_dataframe`.

The doc from DataFrameIterator states : `color_mode: One of `"rgb"`, `"rgba"`, `"grayscale"`

I cannot test right now, but could you try setting "rgba"?

**Comment by cameronbronstein** [comment]
I set 'rgba' and did not receive any errors!
Thanks for the simple suggestion, and I hope the docs can get updated to reflect this.
And thanks for all you do for Keras and the ML community.

**Comment by Dref360** [comment]
I'll leave it open till we fix the doc.
