### ISSUE TITLE
Which one is expected by channel_shift?

### ISSUE THREAD

**Issue by wakamezake** [keras-team/keras-preprocessing#17]
Hello! While runnning [keras-preprocessing(master)/image.py/random_channel_shift](https://github.com/keras-team/keras-preprocessing/blob/master/keras_preprocessing/image.py#L182-L194), I thought it was different from the expected channel_shift behavior.

I think that the expected channel shift movement is old.
#### Original Images(cifar10)
```python
from keras.datasets import cifar10
from keras.preprocessing.image import random_channel_shift
import numpy as np
import matplotlib.pyplot as plt


def plot_tiles(images, rows=5, columns=5):
    pos = 1
    for idx in range(rows*columns):
        plt.subplot(rows, columns, pos)
        img = images[idx]
        plt.imshow(img)
        plt.axis("off")
        pos += 1
    plt.show()


(x_train, y_train), (x_test, y_test) = cifar10.load_data()
sample_images = x_train[:9]/255
channel_shift_range = 0.3
plot_tiles(sample_images, rows=3, columns=3)
```
<img src="https://user-images.githubusercontent.com/7046610/41537111-7432c7ce-7342-11e8-93d6-4f979d3c15a9.png" width=50%>

#### Latest Channel_Shift Images(cifar10)
```python
channel_shift_images_latest = []
for _ in sample_images:
    channel_shift_images_latest.append(_random_channel_shift(_, channel_shift_range, 2))
channel_shift_images_latest = np.array(channel_shift_images_latest)
plot_tiles(channel_shift_images_latest, rows=3, columns=3)
```
[keras-preprocessing(master)/image.py/random_channel_shift](https://github.com/keras-team/keras-preprocessing/blob/master/keras_preprocessing/image.py#L182-L194)
<img src="https://user-images.githubusercontent.com/7046610/41537122-78922896-7342-11e8-97e6-3bce5dcc28d2.png" width=50%>

#### Old Channel_Shift Images(cifar10)
```python
channel_shift_images_old = []
for _ in sample_images:
    channel_shift_images_old.append(random_channel_shift(_, channel_shift_range, 2))
channel_shift_images_old = np.array(channel_shift_images_old)
plot_tiles(channel_shift_images_old, rows=3, columns=3)
```
[keras-preprocessing(old)/image.py/random_channel_shift](https://github.com/keras-team/keras/blob/8532744ad3de309e807ade1b9b6eff9603305b1a/keras/preprocessing/image.py#L178-L199)
<img src="https://user-images.githubusercontent.com/7046610/41537149-8d70fc6a-7342-11e8-9cd3-9ac5dd6ceef4.png" width=50%>

**Comment by Dref360** [comment]
The current behaviour has been in place for more than 2 years now.
See PR : https://github.com/keras-team/keras/pull/2446

**Comment by zhenglilei** [comment]
Hi Frédéric,

I think some changes were unintentionally made to the "random_channel_shift" function from Keras 2.1.6 to Keras 2.2.0 (the separate preprocessing lib). Please check [this PR](https://github.com/keras-team/keras-preprocessing/pull/18) if I am wrong. Thanks.

**Comment by rragundez** [comment]
@Dref360 can we close this issue? It does not seem relevant.

**Comment by jingprism** [comment]
I think there was a mistake with the code. If you input some large value like 200.0, it will produce real channel shifts like mentioned here under "Old Channel_Shift Images(cifar10)": https://github.com/keras-team/keras-preprocessing/issues/223

However, it should be using a float between 0 and 1 rather than a large absolute value.
