### ISSUE TITLE
Is it possible using flow_from_dataframe() to pass the same image-path multiple times to an ImageDataGenerator?

### ISSUE THREAD

**Issue by aarondt** [keras-team/keras-preprocessing#175]
I am trying to balance an unbalanced dataset for image classification. As such, I duplicated the entries of the minority class within my dataframe n-times to match the number of samples of the majority class. This procedure leads to a situation where I have multiple images sharing the same path in my dataframe.

For example my dataframe looks like this:

```
path                          class
C:/image/1.jpg                 "A"
C:/image/1.jpg                 "A
C:/image/2.jpg                 "B"
C:/image/2.jpg                 "B"
```

Now, once I pass the dataframe to my `ImageDataGenerator `using `flow_from_dataframe `it only returns each image exactly once. For example the output would be:

`Found 2 images belonging to 2 classes.`

wheres I would like to have:

`Found 4 images belonging to 2 classes.`

As such, I would like to know if it is possible to use an image multiple times during training using` flow_from_dataframe()` without actually copying the file on hard-drive multiple times? Considering that the image database I am dealing with is rather large, this would save me a huge amount of disk-space.

**Comment by rragundez** [comment]
It is possible by setting the parameters `drop_duplicates=False`, but I recommend you to not do it the way you are doing it but to use the `class_weight` parameter of `fit_generator` to balance your classes.
Here is a blogpost example where I use the `class_weight` parameter  https://blog.godatadriven.com/rod-keras-multi-label
