### ISSUE TITLE
keras ImageDataGenerator not using keras.utils.Sequence

### ISSUE THREAD

**Issue by MarcelBeining** [keras-team/keras-preprocessing#178]
Hi,
according to https://keras.io/models/sequential/#fit_generator it is highly recommended to inherit generators from `keras.utils.Sequence` to  "guarantee the single use of every input per epoch when using use_multiprocessing=True".
However, I saw that the [NumpyIterator](https://github.com/keras-team/keras-preprocessing/blob/master/keras_preprocessing/image/numpy_array_iterator.py), which is used by `ImageDataGenerator` to create a generator does not inherit from `keras.utils.Sequence` but simply from `Iterator`.

As the main purpose of `ImageDataGenerator` is to use it with the `fit_generator `method, it should use `keras.utils.Sequence`. Or is `ImageDataGenerator` using anything that assures whole data usage per epoch, which I am missing?

**Comment by Dref360** [comment]
Iterator inherits from Sequence

**Comment by MarcelBeining** [comment]
D'oh, missed that. Thanks!
