### ISSUE TITLE
flow_from_dataframe() not working with directory None in macOS

### ISSUE THREAD

**Issue by b-freitas** [keras-team/keras-preprocessing#191]
I'm trying to use flow_from_dataframe() with absolute filenames and directory set to None in my macOS Mojave 10.14.3, but the function return a error. See bellow:

/usr/local/lib/python2.7/site-packages/keras_preprocessing/image.pyc in flow_from_dataframe(self, dataframe, directory, x_col, y_col, has_ext, target_size, color_mode, classes, class_mode, batch_size, shuffle, seed, save_to_dir, save_prefix, save_format, subset, interpolation)

/usr/local/lib/python2.7/site-packages/keras_preprocessing/image.pyc in __init__(self, dataframe, directory, image_data_generator, x_col, y_col, has_ext, target_size, color_mode, classes, class_mode, batch_size, shuffle, seed, data_format, save_to_dir, save_prefix, save_format, follow_links, subset, interpolation, dtype)

/usr/local/lib/python2.7/site-packages/keras_preprocessing/image.pyc in _list_valid_filenames_in_directory(directory, white_list_formats, split, class_indices, follow_links, df)

/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.pyc in basename(p)
    112 def basename(p):
    113     """Returns the final component of a pathname"""
--> 114     i = p.rfind('/') + 1
    115     return p[i:]
    116 

AttributeError: 'NoneType' object has no attribute 'rfind'

I'm using the lastest keras-preprocessing (1.0.9) and Python 2.7, but the error continue yet.  

My dataframe example has a column "filenames" and it values are: '/User/User1/images/images_a/images_1a.jpg', 
'/User/User1/images/images_a/images_2a.jpg',
....
'/User/User1/images/images_b/images_1b.jpg', 
....
etc

The y_col is a array containing the columns names with values between 0 and 1 (one_hot). 

datagen.flow_from_dataframe(dataframe=dataframe,
                                                 directory=None,
                                                    x_col='filenames',
                                                    y_col=labels,
                                                    batch_size=32,
                                                    seed=123,
                                                    shuffle=True,
                                                    class_mode='other',                                                    
                                                    target_size=(32,32))

Anyone have some idea about this error?

thanks

**Comment by rragundez** [comment]
Which version of `keras_preprocessing` are you using? It seems to be an old version as the file `image.py` does not exist anymore. Please update the version and try again, you can run
`pip install -U git+https://github.com/keras-team/keras-preprocessing.git`
to update the package.

**Comment by b-freitas** [comment]
@rragundez Thanks for your help.

I already have the 1.0.9 version using pip install and github repository from the keras team, as I mentioned above.

I think maybe something about the value into to variable, based in the line error below:
AttributeError: 'NoneType' object has no attribute 'rfind'

what do you think about it?

**Comment by rragundez** [comment]
please update `pip install -U git+https://github.com/keras-team/keras-preprocessing.git` and test it again. Thanks.

**Comment by rragundez** [comment]
@b-freitas is this still an issue after the update I mentioned above?

**Comment by karolmajek** [comment]
I fixed this error by checking `df.head()` and the error was the separator in my csv file (semicolon instead of the default comma)
adding sep=';' to pd.read_csv fixed the issue
other thing - labels need to be str
