### ISSUE TITLE
Error message with build_generator

### ISSUE THREAD

**Issue by alkra1** [keras-team/keras-preprocessing#194]
An Error just popped-up

for a line ```

Error : TypeError: If class_mode="binary", y_col="Label" column values must be strings.

the code was working fine just before

my code:

df['R_eye'].value_counts() 1 37612 0 37606 Name: R_eye, dtype: int64

**Comment by rragundez** [comment]
Please have a look at #152

**Comment by alkra1** [comment]
Hi,

Thanks for your email.

I looked at it and fixed code, then reposted:

thanks. but this never used to be a problem... ive been running it for weeks. and why does binary require string?
and then i changed to string:

df['R_eye'] = df['R_eye'].apply(str)
is_string_dtype(df['R_eye'])
True
and got same error
TypeError: If class_mode="binary", y_col="R_eye" column values must be strings.

Any advice?
