### ISSUE TITLE
I get the folowing error when i run my code.

### ISSUE THREAD

**Issue by MANOJVONTEDDU** [keras-team/keras-preprocessing#202]
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of keras-preprocessing. You can update with:
`pip install git+git://github.com/keras-team/keras-preprocessing.git --upgrade --no-deps`

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).
![Screenshot from 2019-04-22 00-25-01](https://user-images.githubusercontent.com/16188320/56474268-211d8c00-6495-11e9-99f9-dd4923369eb6.png)
![Screenshot from 2019-04-22 00-25-07](https://user-images.githubusercontent.com/16188320/56474269-237fe600-6495-11e9-8591-12cd42820d33.png)

**Comment by Dref360** [comment]
There are no images in your folder. So it fails.

**Comment by rragundez** [comment]
Addressed at #204
