### ISSUE TITLE
May raise modulo by zero error

### ISSUE THREAD

**Issue by siddheshsathe** [keras-team/keras-preprocessing#203]
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of keras-preprocessing. You can update with:
`pip install git+git://github.com/keras-team/keras-preprocessing.git --upgrade --no-deps`

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Source:** https://github.com/keras-team/keras-preprocessing/blob/6ff9af6971f97f69c39d090be15c2f7d93aa4d6d/keras_preprocessing/image/iterator.py#L85

- Under class `Iterator`, if the initialization happens with 0 number of images for any number of class, it may raise `modulo by zero error`
- Solution would be to assert if `n == 0` while initializing the `Iterator` class.

**Comment by rragundez** [comment]
Solved at #204
