### ISSUE TITLE
Mistake in text_to_sequences documentation

### ISSUE THREAD

**Issue by kareemamrr** [keras-team/keras-preprocessing#213]
I am using Keras' tokenizer to preprocess some texts, I fit the tokenizer on my corpus and generated sequences using "texts_to_sequences" method. When I looked at the docs the method listed was called "texts_to_word_sequences" and it stated that it took a string as an argument (both on docs website and in the source code available on Github), whereas the one available for actual use is called "texts_to_sequence" and it says that it takes a list of string as an argument (this one is not either in the docs or in the source code).

**Comment by joshz123** [comment]
Isn't the documentation hosted on the main keras repo. Would this issue be better suited there?
