### ISSUE TITLE
add prefetch mechanism

### ISSUE THREAD

**Issue by Seanspt** [keras-team/keras-preprocessing#217]

**Comment by Seanspt** [comment]
CPU usually have several cores. Is it possible to load images concurrently and pre-load several batches in advance to fully utilize GPU?

**Comment by Dref360** [comment]
When you call fit_generator, if you specify `workers=4` and `use_multiprocessing=True`, the data will be loaded asynchronously on 4 workers.

**Comment by Seanspt** [comment]
Didn't realize it's implemented at fit phase. Thought it was kind of a dataset behavior.
Thanks. I'll close the issue then.
