### ISSUE TITLE
Avoid Package Dependencies

### ISSUE THREAD

**Issue by brunoalano** [keras-team/keras-preprocessing#22]
From a perspective from who only want to use the `sequence.pad_sequences` module and don't want to do a shallow copy of it, I believe that a better aproach for this project would be to avoid any dependency, or just use `numpy`.

We can do like all packages do for `matplotlib` for example, displaying a warning to the user that a optional dependency are required for that process.

Packages to remove from dependencies:
- Keras
- scipy

**Comment by Dref360** [comment]
Why is pip install --no-deps not the solution?
