### ISSUE TITLE
ImageDataGenerator for Image Preprocessing in keras does not support S3 path

### ISSUE THREAD

**Issue by revy123** [keras-team/keras-preprocessing#220]
The ImageDataGenerator for Image Preprocessing in keras does not support S3 path. It expects the path to be a local directory and since it is not able to find that, it throws a FILENOTFOUNDERROR.

Moving forward, I will have to download the content from s3 to the sagemaker notebook instance and then perform the preprocessing on it. 

Is there any way this issue can be solved. Thank you

**Comment by rragundez** [comment]
Hi @revy123,

There is no plan to implement this feature.

**Comment by Naivedh** [comment]
> 
> 
> The ImageDataGenerator for Image Preprocessing in keras does not support S3 path. It expects the path to be a local directory and since it is not able to find that, it throws a FILENOTFOUNDERROR.
> 
> Moving forward, I will have to download the content from s3 to the sagemaker notebook instance and then perform the preprocessing on it.
> 
> Is there any way this issue can be solved. Thank you

How did you solve the issue?
