### ISSUE TITLE
Function load_img return white (full 255) image on loading gray image

### ISSUE THREAD

**Issue by Dok11** [keras-team/keras-preprocessing#227]
- [x] Check that you are up-to-date with the master branch of keras-preprocessing. You can update with:
`pip install git+git://github.com/keras-team/keras-preprocessing.git --upgrade --no-deps`

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

In this code:
```py
import os
from keras_preprocessing.image import load_img, img_to_array

file = os.path.join(os.getcwd(), 'test-img.png')
image_loaded = load_img(file, target_size=(8, 4))
image = img_to_array(image_loaded)

print(image)
```

I got
```
[[[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]
 ...
 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]]
```

But image not white, image pretty gray, look:
![test-img](https://user-images.githubusercontent.com/2697890/61909161-14984c00-af3a-11e9-95e6-491b4abbd1ae.png)

Image and script int this archive: 
[script.zip](https://github.com/keras-team/keras-preprocessing/files/3433303/script.zip)

P.S. With jpg this function works correctly

**Comment by rragundez** [comment]
This is an issue with the PIL package, calling `convert` produces the behavior.

```
from PIL import Image

img = Image.open('test-img.png')
img = img.convert('L')
img
```
