### ISSUE TITLE
pass `order` to affine_transform

### ISSUE THREAD

**Issue by OmriTreidel** [keras-team/keras-preprocessing#23]
The method `apply_affine_transform` is a wrapper `scipy.ndimage.interpolation.affine_transform` that has a parameter `order` which is the order a a spline interpolation. Not being able to pass this parameter causes a problem when generating random transformation of labeled images since it results in non-integer values.

for example: 

for a given labels (each integer is a class label) 
```python 
[[2 2 0 2 2]
 [1 3 2 3 1]
 [2 1 0 1 2]
 [3 1 0 2 0]
 [3 1 3 2 1]]
```

it transformed to 
```python 
[[2.289865   1.7110896  1.8507836  2.172145   0.15832195]
 [3.         2.2037435  1.0774351  1.4194988  2.3764393 ]
 [3.         1.4194988  0.39426237 0.49894607 1.7452569 ]
 [1.8929222  1.7380519  1.7849773  2.         1.2062019 ]
 [1.2646285  2.8956027  2.2367117  1.3144331  0.23671168]]
```

Which are clearly not valid class labels. I dag around and found that the reason is the hard coded `order` in https://github.com/keras-team/keras-preprocessing/blob/master/keras_preprocessing/image.py line 323. 

being able to pass this parameter would enable correct data augmentation for image segmentation. 

I have made a small path to fix this issue so i'll create a PR soon.

**Comment by rragundez** [comment]
@Dref360 this issue cna be closed as the feature has been merged into master.
