### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by projectcatdog** [keras-team/keras-preprocessing#235]
I'm using Python 3 in Google Colab. I'm receiving this error:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-15-a9fd07e00cb9> in <module>()
     30 target_size = (64, 64),
     31 batch_size = 32,
---> 32 class_mode = 'binary')
     33 test_set = test_datagen.flow_from_directory('E:\\Project\\dataset\\test_set',
     34 target_size = (64, 64),

1 frames
/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/directory_iterator.py in __init__(self, directory, image_data_generator, target_size, color_mode, classes, class_mode, batch_size, shuffle, seed, data_format, save_to_dir, save_prefix, save_format, follow_links, subset, interpolation, dtype)
    104         if not classes:
    105             classes = []
--> 106             for subdir in sorted(os.listdir(directory)):
    107                 if os.path.isdir(os.path.join(directory, subdir)):
    108                     classes.append(subdir)

FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Project\\dataset\\training_set'

What am I doing wrong? I'm sure with the folder's path. I tried Google Drive (after mounting) and it still doesn't work.

**Comment by rragundez** [comment]
Hi @projectcatdog, I think the exception raised is very clear. You're probably doing something wrong  in Google Colab and the code is running somewhere else then what you think (where the images are).
