### ISSUE TITLE
Is Keras ImageDataGenerator thread safe?

### ISSUE THREAD

**Issue by ahnchive** [keras-team/keras-preprocessing#237]
I'm using the latest version of keras (2.2.4) and keras-preprocessing (1.10.0) and trying to use ImageDataGenerator with multiprocessing and multi worker features. But when I add more than one workers, it outputs warnings that it may duplicate the data as below.

> Using a generator with use_multiprocessing=True and multiple workers may duplicate your data. Please consider using the keras.utils.Sequence class. UserWarning('Using a generator with use_multiprocessing=True

When I looked at the source code, the Iterator of ImageDataGenerator actually inherits the sequence class. Then is this warning just a bug that I can ignore? Can you confirm that keras ImageDataGenerator is thread safe?

**Comment by Dref360** [comment]
We fixed that issue a while ago, but it was recently merged into Keras 2.3.0. Please upgrade. Sorry for the delay.
