### ISSUE TITLE
Can multi-label images be loaded?

### ISSUE THREAD

**Issue by kingdsz** [keras-team/keras-preprocessing#238]
I'm making a group emotion prediction. A picture contains two tags, one of which is category [positive, negative, neutral], and the others is cohesion score，this is numerical data. How should I load my image with keras? If I can't load images with keras, how do you suggest I load images? Tf. data. Datasets?

Thank you for answering my question.

**Comment by Vijayabhaskar96** [comment]
You need to create your own custom generator to train the model.

**Comment by kingdsz** [comment]
Thank you。

**Comment by rragundez** [comment]
You're doinoing a multi-task learning poblem. You can usse the multi-ouput functionality of the generator. Here an example: https://gist.github.com/rragundez/8b1b9e190abef8ffb6d93f03f8e0e091
There have two classification tasks, in your case you have a classification and a regression task. You need to convert thee labels to label index first for the classification and leave the score as is annd use the `raw` mode.
