### ISSUE TITLE
docs(image-generator): clarify 'classes' argument in .flow_from_dataframe

### ISSUE THREAD

**Issue by thetric** [keras-team/keras-preprocessing#240]
I think the behavior of the `classes` argument of [`ImageDataGenerator.flow_from_dataframe`](https://keras.io/preprocessing/image/#flow_from_dataframe) is a bit confusing. The `DataFrameIterator` internally sorts the user defined classes and mixes up the generated labels:

```py
import pandas as pd
from keras_preprocessing.image import ImageDataGenerator

df = pd.DataFrame(data={'filename': ['dog.jpg', 'cat.jpg'], 'class': ['dog', 'cat']})
CLASSES = ['dog', 'cat']
EXPECTED_LABELS = [0, 1]
gen = ImageDataGenerator().flow_from_dataframe(df, classes=CLASSES, class_mode='binary')
print("expected labels: {}".format(EXPECTED_LABELS))
print("actual labels: {}".format(gen.labels))
assert gen.labels == EXPECTED_LABELS
```

output:
```
Found 2 validated image filenames belonging to 2 classes.
expected labels: [0, 1]
actual labels: [1, 0]
Traceback (most recent call last):
  File "keras-idg-bug.py", line 10, in <module>
    assert gen.labels == EXPECTED_LABELS
AssertionError
```

Another point is that the iterator silently drops rows from the dataframe if the class is not in the `classes` argument:

```py
import pandas as pd
from keras_preprocessing.image import ImageDataGenerator

df = pd.DataFrame(data={'filename': ['dog.jpg', 'horse.jpg'], 'class': ['dog', 'horse']})
CLASSES = ['dog', 'cat']
gen = ImageDataGenerator().flow_from_dataframe(df, classes=CLASSES, class_mode='binary')
print("actual labels: {}".format(gen.labels))
```

```
Found 1 validated image filenames belonging to 2 classes.
actual labels: [1]
```

This behavior should be mentioned in the API docs.

**Comment by Vijayabhaskar96** [comment]
Both are expected behaviors, 
The correct way to access the labels is by mapping the labels with the gen.class_indices

> Another point is that the iterator silently drops rows from the dataframe if the class is not in the classes argument

Of course, if a file is not found or you explicitly asked the generator to find only images from classes you specified, the rows with labels "horse" which is not specified will be skipped. This is not silent as you can see the number of "validated" images. This avoids the problem of including corrupted images and also allows you to train only on images that belong to say 2 classes when you have more than 2 classes of images in your dataset.

**Comment by rragundez** [comment]
@thetric I sort of agree that the naming is a bit confusing, there should be a clear distinction between `classes`, `labels`, `class_indices` and `label_indices` but unfortunately several generators are using what I think is the wrong definition sometimes and is very difficult to deprecate such behavior with the current wide adaptation of such behavior. Also the source code to be honest sometimes uses the same attribute to capture different definitions. Hopefully we can do a better job moving forward.
