### ISSUE TITLE
Keras flow from dataframe: IndexError: list index out of range in keras preprocessing Iterator

### ISSUE THREAD

**Issue by ShivamPanchal** [keras-team/keras-preprocessing#241]
I loaded the data from kaggle kernel to my machine for reprodicing, now the code is not working, but works on the keras on same python environment.

Here is the code and the bug.

```
def flow_from_dataframe(img_data_gen, in_df, path_col, y_col, **dflow_args):
    base_dir = os.path.dirname(in_df[[path_col]].values[0])
    print('## Ignore next message from keras, values are replaced anyways')
    df_gen = img_data_gen.flow_from_directory(base_dir, 
                                     class_mode = 'sparse',
                                    **dflow_args)
    df_gen.filenames = in_df[path_col].values
    df_gen.classes = np.stack(in_df[y_col].values)
    df_gen.samples = in_df.shape[0]
    df_gen.n = in_df.shape[0]
    df_gen._set_index_array()
    df_gen.directory = '' # since we have the full path
    print('Reinserting dataframe: {} images'.format(in_df.shape[0]))
    return df_gen


train_gen = flow_from_dataframe(core_idg, train_df, 
                             path_col = 'path',
                            y_col = 'disease_vec', 
                            target_size = IMG_SIZE,
                             color_mode = 'rgb',
                            batch_size = 32)

valid_gen = flow_from_dataframe(core_idg, valid_df, 
                             path_col = 'path',
                            y_col = 'disease_vec', 
                            target_size = IMG_SIZE,
                             color_mode = 'rgb',
                            batch_size = 256) # we can use much larger batches for evaluation
# used a fixed dataset for evaluating the algorithm
test_X, test_Y = next(flow_from_dataframe(core_idg, 
                               valid_df, 
                             path_col = 'path',
                            y_col = 'disease_vec', 
                            target_size = IMG_SIZE,
                             color_mode = 'rgb',
                            batch_size = 1024)) # one big batch

t_x, t_y = next(train_gen)
fig, m_axs = plt.subplots(4, 4, figsize = (16, 16))
```

I am able to see the paths and path lists, but not sure, where it is coming from.

```
Found 0 images belonging to 0 classes.
Reinserting dataframe: 10000 images
Traceback (most recent call last):
  File "main.py", line 181, in <module>
    batch_size = 32)) # one big batch
  File "/home/user/.conda/envs/test_env/lib/python3.6/site-packages/keras_prepro         cessing/image/iterator.py", line 104, in __next__
    return self.next(*args, **kwargs)
  File "/home/user/.conda/envs/test_env/lib/python3.6/site-packages/keras_prepro         cessing/image/iterator.py", line 116, in next
    return self._get_batches_of_transformed_samples(index_array)
  File "/home/user/.conda/envs/test_env/lib/python3.6/site-packages/keras_prepro         cessing/image/iterator.py", line 227, in _get_batches_of_transformed_samples
    img = load_img(filepaths[j],
```

**Comment by rragundez** [comment]
Seems like you created custom `flow_from_dataframe` but the error comes from `flow_from_directory`. Please first make sure thatt images are found. You probably have something wrong with the paths or file extensions.

**Comment by hugokitano** [comment]
Hi Pranav, were you able to fix this? I have the same exact bug and have no solutions

**Comment by elisim** [comment]
The error occurs because ```filepaths``` is empty list. Add to ```filepaths``` the images paths:

```python
df_gen.filepaths.extend(df_gen.filenames)
```

**Comment by Janey-B** [comment]
Did somebody find a solution for that? I have the same error:
```
def flow_from_dataframe(img_data_gen, in_df, path_col, y_col, **dflow_args):
    base_dir = os.path.dirname(in_df[path_col].values[0])
    print('## Ignore next message from keras, values are replaced anyways')
    df_gen = img_data_gen.flow_from_directory(base_dir, 
                                     class_mode = 'sparse',
                                    **dflow_args)
    df_gen.filenames = in_df[path_col].values
    df_gen.classes = np.stack(in_df[y_col].values)
    df_gen.samples = in_df.shape[0]
    df_gen.n = in_df.shape[0]
    df_gen._set_index_array()
    df_gen.directory = '' 
    print('Reinserting dataframe: {} images'.format(in_df.shape[0]))
    return df_gen

#Create training array
#On the fly with keras flow_from_dataframe 
datagen= ImageDataGenerator(rescale=1./255)
datagen_train = ImageDataGenerator(rescale=1./255)

train_gen = flow_from_dataframe( 
    datagen, 
    train_df, 
    path_col = 'full_path', 
    y_col = 'target_vector', 
    target_size = image_size, 
    color_mode = 'grayscale', 
    batch_size = 32)

valid_gen = flow_from_dataframe(
    datagen,
    test_df, 
    path_col = 'full_path', 
    y_col = 'target_vector', 
    target_size = image_size,
    color_mode = 'grayscale', 
    batch_size = 128)

test_X, test_Y = next(flow_from_dataframe(datagen, test_df, path_col = 'full_path', y_col = 'target_vector', 
                                          target_size = (img_rows, img_cols), color_mode = 'grayscale', 
                                          batch_size = 2048))
```

which gives me: 
```
Found 0 images belonging to 0 classes.
Reinserting dataframe: 13462 images
IndexError: list index out of range
```
pointing to 
```
lib/python3.7/site-packages/keras_preprocessing/image/iterator.py in _get_batches_of_transformed_samples(self, index_array)
    225         filepaths = self.filepaths
    226         for i, j in enumerate(index_array):
--> 227             img = load_img(filepaths[j],
    228                            color_mode=self.color_mode,
    229                            target_size=self.target_size,
```

`train_gen.filenames` and `valid_gen.filenames` gives me the right array of full paths to the images. 


Tried to add elisims solution into the `def flow_from_dataframe` function
```
def flow_from_dataframe(img_data_gen, in_df, path_col, y_col, **dflow_args):
    base_dir = os.path.dirname(in_df[path_col].values[0])
    print('## Ignore next message from keras, values are replaced anyways')
    df_gen = img_data_gen.flow_from_directory(base_dir, 
                                     class_mode = 'sparse',
                                    **dflow_args)
    df_gen.filenames = in_df[path_col].values
    df_gen.filepaths.extend(df_gen.filenames)
    df_gen.classes = np.stack(in_df[y_col].values)
    df_gen.samples = in_df.shape[0]
    df_gen.n = in_df.shape[0]
    df_gen._set_index_array()
    df_gen.directory = '' 
    print('Reinserting dataframe: {} images'.format(in_df.shape[0]))
    return df_gen
```
but it gives `ValueError: setting an array element with a sequence.`

I am using tensorflow 2.1.0. 

Any help appreciated.

**Comment by anikola** [comment]
> Did somebody find a solution for that? I have the same error:
> 
> ```
> def flow_from_dataframe(img_data_gen, in_df, path_col, y_col, **dflow_args):
>     base_dir = os.path.dirname(in_df[path_col].values[0])
>     print('## Ignore next message from keras, values are replaced anyways')
>     df_gen = img_data_gen.flow_from_directory(base_dir, 
>                                      class_mode = 'sparse',
>                                     **dflow_args)
>     df_gen.filenames = in_df[path_col].values
>     df_gen.classes = np.stack(in_df[y_col].values)
>     df_gen.samples = in_df.shape[0]
>     df_gen.n = in_df.shape[0]
>     df_gen._set_index_array()
>     df_gen.directory = '' 
>     print('Reinserting dataframe: {} images'.format(in_df.shape[0]))
>     return df_gen
> 
> #Create training array
> #On the fly with keras flow_from_dataframe 
> datagen= ImageDataGenerator(rescale=1./255)
> datagen_train = ImageDataGenerator(rescale=1./255)
> 
> train_gen = flow_from_dataframe( 
>     datagen, 
>     train_df, 
>     path_col = 'full_path', 
>     y_col = 'target_vector', 
>     target_size = image_size, 
>     color_mode = 'grayscale', 
>     batch_size = 32)
> 
> valid_gen = flow_from_dataframe(
>     datagen,
>     test_df, 
>     path_col = 'full_path', 
>     y_col = 'target_vector', 
>     target_size = image_size,
>     color_mode = 'grayscale', 
>     batch_size = 128)
> 
> test_X, test_Y = next(flow_from_dataframe(datagen, test_df, path_col = 'full_path', y_col = 'target_vector', 
>                                           target_size = (img_rows, img_cols), color_mode = 'grayscale', 
>                                           batch_size = 2048))
> ```
> 
> which gives me:
> 
> ```
> Found 0 images belonging to 0 classes.
> Reinserting dataframe: 13462 images
> IndexError: list index out of range
> ```
> 
> pointing to
> 
> ```
> lib/python3.7/site-packages/keras_preprocessing/image/iterator.py in _get_batches_of_transformed_samples(self, index_array)
>     225         filepaths = self.filepaths
>     226         for i, j in enumerate(index_array):
> --> 227             img = load_img(filepaths[j],
>     228                            color_mode=self.color_mode,
>     229                            target_size=self.target_size,
> ```
> 
> `train_gen.filenames` and `valid_gen.filenames` gives me the right array of full paths to the images.
> 
> Tried to add elisims solution into the `def flow_from_dataframe` function
> 
> ```
> def flow_from_dataframe(img_data_gen, in_df, path_col, y_col, **dflow_args):
>     base_dir = os.path.dirname(in_df[path_col].values[0])
>     print('## Ignore next message from keras, values are replaced anyways')
>     df_gen = img_data_gen.flow_from_directory(base_dir, 
>                                      class_mode = 'sparse',
>                                     **dflow_args)
>     df_gen.filenames = in_df[path_col].values
>     df_gen.filepaths.extend(df_gen.filenames)
>     df_gen.classes = np.stack(in_df[y_col].values)
>     df_gen.samples = in_df.shape[0]
>     df_gen.n = in_df.shape[0]
>     df_gen._set_index_array()
>     df_gen.directory = '' 
>     print('Reinserting dataframe: {} images'.format(in_df.shape[0]))
>     return df_gen
> ```
> 
> but it gives `ValueError: setting an array element with a sequence.`
> 
> I am using tensorflow 2.1.0.
> 
> Any help appreciated.

I have exactly the same issue.. did you found any work around???

**Comment by tjliupeng** [comment]
The same issue for me. Any workaround?

**Comment by 07061999** [comment]
> The error occurs because `filepaths` is empty list. Add to `filepaths` the images paths:
> 
> ```python
> df_gen.filepaths.extend(df_gen.filenames)
> ```

Hey can elaborate the solution
def flow_from_dataframe(img_data_gen, in_df, path_col, y_col, **dflow_args):
    base_dir = os.path.dirname(in_df[path_col].values[0])
    print('## Ignore next message from keras, values are replaced anyways')
    df_gen = img_data_gen.flow_from_directory(base_dir, 
                                     class_mode = 'sparse',
                                    **dflow_args)
    df_gen.filenames = in_df[path_col].values
    print("xxxxxxxxxxxxxxxxx",base_dir)
    df_gen.classes = np.stack(in_df[y_col].values)
    df_gen.samples = in_df.shape[0]
    df_gen.n = in_df.shape[0]
    df_gen._set_index_array()
    df_gen.directory = '' # since we have the full path
    print('Reinserting dataframe: {} images'.format(in_df.shape[0]))
    return df_gen
where should i add your solution?

**Comment by HsMirlohi** [comment]
> > The error occurs because `filepaths` is empty list. Add to `filepaths` the images paths:
> > ```python
> > df_gen.filepaths.extend(df_gen.filenames)
> > ```
> 
> Hey can elaborate the solution
> def flow_from_dataframe(img_data_gen, in_df, path_col, y_col, **dflow_args):
> base_dir = os.path.dirname(in_df[path_col].values[0])
> print('## Ignore next message from keras, values are replaced anyways')
> df_gen = img_data_gen.flow_from_directory(base_dir,
> class_mode = 'sparse',
> **dflow_args)
> df_gen.filenames = in_df[path_col].values
> print("xxxxxxxxxxxxxxxxx",base_dir)
> df_gen.classes = np.stack(in_df[y_col].values)
> df_gen.samples = in_df.shape[0]
> df_gen.n = in_df.shape[0]
> df_gen._set_index_array()
> df_gen.directory = '' # since we have the full path
> print('Reinserting dataframe: {} images'.format(in_df.shape[0]))
> return df_gen
> where should i add your solution?

Hi, could you find the solution? I have the same problem
