### ISSUE TITLE
OSError: [Errno 24] Too many open files when using `load_img`

### ISSUE THREAD

**Issue by duhaime** [keras-team/keras-preprocessing#260]
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of keras-preprocessing. You can update with:
`pip install git+git://github.com/keras-team/keras-preprocessing.git --upgrade --no-deps`

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

```python
from keras.preprocessing.image import load_img, save_img, array_to_img
import numpy as np

im = array_to_img(np.random.rand(300,300,3))
save_img('im.jpg', im)

# read in the image lots of times
# throws OSError: [Errno 24] Too many open files: 'im.jpg'
images = [load_img('im.jpg') for i in range(2**16)]
```

**Comment by Smankusors** [comment]
Hmm wait, is this issue is still open or already solved by #261? Shouldn't this be closed?

**Comment by duhaime** [comment]
Interesting, can you show the snippet that's causing this for you, and post your keras and/or keras_preprocessing versions? Here's a minimal snippet you could use for testing:

```
import numpy as np
from keras_preprocessing.image.utils import load_img, save_img, array_to_img
# or from keras.preprocessing.image import load_img, save_img, array_to_img

im = array_to_img(np.random.rand(300,300,3))
save_img('im.jpg', im)

# read in the image lots of times
# throws OSError: [Errno 24] Too many open files: 'im.jpg'
images = [load_img('im.jpg') for i in range(2**16)]
```

**Comment by Smankusors** [comment]
oh no no no, I already tested your snippet (on Google Colab) and it's not throwing errors. Just wondering why this is not closed? 😅

**Comment by Dref360** [comment]
Thank you I'll close!
