### ISSUE TITLE
"classes" not working on flow_from_dataframe? 

### ISSUE THREAD

**Issue by qinst64** [keras-team/keras-preprocessing#267]
![image](https://user-images.githubusercontent.com/16003088/70912694-76736280-204f-11ea-8ecf-38b9fb957636.png)
The parameter `classes` of `flow_from_dataframe`  is working as above documentation  
as [the code](https://github.com/keras-team/keras-preprocessing/blob/master/keras_preprocessing/image/dataframe_iterator.py#L243) dismisses order
```python
        if classes:
            classes = set(classes)  # sort and prepare for membership lookup
            df[y_col] = df[y_col].apply(lambda x: remove_classes(x, classes))
        else:
            classes = set()
            for v in df[y_col]:
                if isinstance(v, (list, tuple)):
                    classes.update(v)
                else:
                    classes.add(v)
        return df.dropna(subset=[y_col]), sorted(classes)
```
Reproducible example:
[https://github.com/keras-team/keras/issues/13637](https://github.com/keras-team/keras/issues/13637)

**Comment by rragundez** [comment]
The `classes` parameter is for the user to set which classes to use. If given in different order they still define the same classes to use, therefore the result should be the same. Do you think is the documentation which needs to change?
