### ISSUE TITLE
def flow_from_directory，i want to know more about source code how to return lable，but i can not find source code ,only Arguments.

### ISSUE THREAD

**Issue by mk123qwe** [keras-team/keras-preprocessing#272]
def flow_from_directory，i want to know more about source code
how to return lable，but i can not find source code ,only Arguments.

**Comment by Dref360** [comment]
flow_from_directory returns a keras.utils.Sequence defined here: https://github.com/keras-team/keras-preprocessing/blob/master/keras_preprocessing/image/directory_iterator.py
