### ISSUE TITLE
Missing 1.1.1 and 1.1.2 tags

### ISSUE THREAD

**Issue by sclarkson** [keras-team/keras-preprocessing#305]
These releases are present on PyPI but without tags on GitHub.

**Comment by h-vetinari** [comment]
Please tag these if possible.

If anyone is looking for them, this is [1.1.1](https://github.com/keras-team/keras-preprocessing/commit/3e719d37080dfc76fc33888ce7232cc74363b79c) and [1.1.2](https://github.com/keras-team/keras-preprocessing/commit/4538765fd369def80f81ad977bcf8e40e58c2f82)

**Comment by Dref360** [comment]
Done
https://github.com/keras-team/keras-preprocessing/tags
