### ISSUE TITLE
Is x = np.copy(x) necessary in fit function of class ImageDataGenerator?

### ISSUE THREAD

**Issue by DominickZhang** [keras-team/keras-preprocessing#33]
Hi! When I was running my codes, the memory error occurred in fit function. I have changed the type of `img1` as `float32` in order not to copy `x` in `x = np.asarray(x, dtype = backend.floatx())`, which is shown in the picture below. Although there are many ways to solve this problem, I am curious about whether `x = np.copy(x)` is needed. It seems that an `if...else...` statement to decide whether to adjust the order of x can avoid unnecessary memory allocation, especially when `x` is a huge matrix. 
Many thanks!

<img width="395" alt="wx20180803-000236 2x" src="https://user-images.githubusercontent.com/16048179/43625344-27f73eb0-96b2-11e8-9c5e-f686b21c4c04.png">

The following is the codes from Line 1205 to 1232 in image.py.
```
        x = np.asarray(x, dtype=backend.floatx())
        if x.ndim != 4:
            raise ValueError('Input to `.fit()` should have rank 4. '
                             'Got array with shape: ' + str(x.shape))
        if x.shape[self.channel_axis] not in {1, 3, 4}:
            warnings.warn(
                'Expected input to be images (as Numpy array) '
                'following the data format convention "' +
                self.data_format + '" (channels on axis ' +
                str(self.channel_axis) + '), i.e. expected '
                'either 1, 3 or 4 channels on axis ' +
                str(self.channel_axis) + '. '
                'However, it was passed an array with shape ' +
                str(x.shape) + ' (' + str(x.shape[self.channel_axis]) +
                ' channels).')

        if seed is not None:
            np.random.seed(seed)

        x = np.copy(x)
        if augment:
            ax = np.zeros(
                tuple([rounds * x.shape[0]] + list(x.shape)[1:]),
                dtype=backend.floatx())
            for r in range(rounds):
                for i in range(x.shape[0]):
                    ax[i + r * x.shape[0]] = self.random_transform(x[i])
            x = ax
```

**Comment by Dref360** [comment]
I think we have to keep it.
`x` is modified by every option but `zca_whitening`.
Keeping the original array wouldn't be user-friendly.
