### ISSUE TITLE
version in setup.py, 1.0.1,  is incorrect for the 1.0.2 tag

### ISSUE THREAD

**Issue by jjhelmus** [keras-team/keras-preprocessing#41]
The [version recorded in the setup.py file for the 1.0.2 tag](https://github.com/keras-team/keras-preprocessing/blob/1.0.2/setup.py#L24) is 1.0.1, which is incorrect.  The sdist on PyPI has the correct version in the setup.py file.  

This can causes issues if a checkout of the git tag is used as the mean to install keras-preprocessing as the incorrect version will be recorded in the metadata.

I do not think anything should be done to fix this as changing a tag is a bad procedure.  I think it is useful to have this in the issue tracker in case anyone else runs into the issue.

**Comment by Dref360** [comment]
Thanks for the info, we'll try to be more consistent
