### ISSUE TITLE
Pip releases vs github releases

### ISSUE THREAD

**Issue by ixil** [keras-team/keras-preprocessing#42]
Hi, I'm a maintainer for https://aur.archlinux.org/pkgbase/python-keras-preprocessing/
The latest pip release is 1.0.3 whereas the latest github release is 1.0.2 (albeit with a wrong version number in the setup.py) 
Are the pip releases the preferred official release, or should I stick to using the github releases?

**Comment by Dref360** [comment]
Fixed, 1.0.3 is released on Github as well
