### ISSUE TITLE
Wrong link in the docs

### ISSUE THREAD

**Issue by fepegar** [keras-team/keras-preprocessing#47]
There is something wrong with this link in the [Image Preprocessing docs](https://keras.io/preprocessing/image/).:
https://github.com/keras-team/keras-preprocessing/blob/45fc4a0bc3d587a337bec93ac01aeeb1e6cc913b/keras_preprocessing/image.py#L886-L888

When I hover on it, I see at the bottom of my browser this URL:
```
https://gist.github.com/fchollet/        0830affa1f7f19fd47b06d4cf89ed44d
```
and when I click on it, it leads me to
```
https://gist.github.com/fchollet/%20%20%20%20%20%20%20%200830affa1f7f19fd47b06d4cf89ed44d
```

I can reproduce on Chrome and Firefox.

**Comment by rragundez** [comment]
The link in the documentation works as expected. If there is an issue it's probably related to the browser functionality you mentioned.

**Comment by fepegar** [comment]
It works for me as well now.
