### ISSUE TITLE
How to get flow_from_directory accept absolute path of images as input

### ISSUE THREAD

**Issue by lixiangchun** [keras-team/keras-preprocessing#56]
I learned from the manual page of `flow_from_directory`, the first argument passed to `flow_from_directory` is a directory. Sometimes, it's also convenient to pass the path of images if the images are placed in multiple directories. If we could get `flow_from_directory` to accept images in the following format:

/path1/img1.jpg  cat
/path2/img2.jpg dog

The first column is the absolute path to the image, and the second column is the class names.

**Comment by Dref360** [comment]
Have you looked into flow_from_dataframe?

**Comment by qinst64** [comment]
#67 
Tried but `flow_from_dataframe` was not working:  `x_col` needs to be filename only?

**Comment by rragundez** [comment]
This issue has been resolved in the current version, as x_col accepts absolute paths. It can be closed. @Dref360
