### ISSUE TITLE
flow_from_dataframe with multiple dtype entries

### ISSUE THREAD

**Issue by michaelStettler** [keras-team/keras-preprocessing#57]
I am trying to use the flow_from_dataframe() function but run on a KeyError: nan error. 

My csv file is as follow:
subDirectory_filePath, expression
img_1, 0
img_2, 3
...
img_n, 0

therefore the first argument is a string while the other one is a integer. I have tried to follow that tuorial: 
[Tutorial on Keras ImageDataGenerator with flow_from_dataframe](https://medium.com/@vijayabhaskar96/tutorial-on-keras-imagedatagenerator-with-flow-from-dataframe-8bd5776e45c1)

and thus my code is: 

    train_datagen = ImageDataGenerator(rescale=1. / 255,horizontal_flip=False)
    df_train = pd.read_csv(data['csv_train_file'], dtype={'subDirectory_filePath': str, 'expression': int})
    train_generator = train_datagen.flow_from_dataframe(
        dataframe=df_train,
        directory=data['img_dir'],
        x_col='subDirectory_filePath',
        y_col='expression',
        has_ext=True,
        class_mode="categorical",
        target_size=(model_params['img_height'], model_params['img_width']),
        batch_size=model_params['batch_size']
        #save_to_dir='test_train'
    )

and get the following issues:

```
Found 427298 images belonging to 11 classes.

Traceback (most recent call last):
  File "train_model.py", line 250, in <module>
    train_model(model_name=model_name, dataset=dataset, mode=mode, weights=weights, computer=computer, run=run)
  File "train_model.py", line 198, in train_model
    train_generator, validation_generator = get_csv_generator(data, model_params, da, extended=False)
  File "train_model.py", line 121, in get_csv_generator
    batch_size=model_params['batch_size']
  File "/home/michael/.local/lib/python3.5/site-packages/keras_preprocessing/image.py", line 1108, in flow_from_dataframe
    interpolation=interpolation)
  File "/home/michael/.local/lib/python3.5/site-packages/keras_preprocessing/image.py", line 2168, in __init__
    self.classes = np.array([self.class_indices[cls] for cls in classes])
  File "/home/michael/.local/lib/python3.5/site-packages/keras_preprocessing/image.py", line 2168, in <listcomp>
    self.classes = np.array([self.class_indices[cls] for cls in classes])
KeyError: nan
```

Furthermore, while printing my csv file I can see that it is full of NaN such as:
subDirectory_filePath                                                            expression                               
002276d73d5822544f39d86b45098e67f84f78cd8edcba8...     NaN
01807ce4c37cc4463bd06a966a4043edc14864a0075ff78...     NaN

I am guessing that my issue is something with loading my csv file, I have first tried without the dtype dictionary but the same error occur.

Any help much appreciated

**Comment by michaelStettler** [comment]
I figure out the issues thanks to @Vijayabhaskar96  and his help. 

The main issues was my data format folder. My images where stored as follow: 
```
folder
    subfolder_1
        img_1
        img_2
       ...
    subfolder_2
        img_x
        img_y
        ...
```
while my csv file was then on the form of: 

```
path       label
subfolder_1/img_1.jpg 0
subfolder_1/img_2.jpg 1
...
```


Thus I wrote a small function to move my images to a single folder and remove the subfolder path from my csv file to have my data on the form

```
new_folder
    img_1
    img_2
    img_x
    img_y
    ...
```
 and my csv file as:
```
path       label
img_1.jpg     0
img_2.jpg     1
...
```

**Comment by Vijayabhaskar96** [comment]
I have written a more detailed article here as I mentioned before. https://medium.com/@vijayabhaskar96/tutorial-on-keras-flow-from-dataframe-1fd4493d237c

**Comment by zhezhang77** [comment]
Modify the function '_list_valid_filenames_in_directory' may compatible with @michaelStettler 's original csv without moving images into another folder.
```
-- folder structure --
folder
    subfolder_1
        img_1
        img_2
       ...
    subfolder_2
        img_x
        img_y
        ...

-- csv file--
path                  label
subfolder_1/img_1.jpg 0
subfolder_1/img_2.jpg 1
...
```

```python
def _list_valid_filenames_in_directory(directory, white_list_formats, split,
                                       class_indices, follow_links, df=False):
...
    if df:
        filenames = []
        for root, fname in valid_files:
            #filenames.append(os.path.basename(fname))                   #<- ORG
            absolute_path = os.path.join(root, fname)                    #<- NEW
            relative_path = os.path.relpath(absolute_path, directory)    #<- NEW
            filenames.append(relative_path)                              #<- NEW
        return filenames
  ...
    return classes, filenames
```

**Comment by AlaaEzzeldin** [comment]
Hello, I'm facing the same problem but is there anyway to solve that without the need to move all images to one folder?

**Comment by Vijayabhaskar96** [comment]
you can create a dataframe which has absolute paths of all the images and it's respective classes,pass it to flow from dataframe and set the directory=None,also make sure you're using the latest GitHub version

**Comment by AlaaEzzeldin** [comment]
> you can create a dataframe which has absolute paths of all the images and it's respective classes,pass it to flow from dataframe and set the directory=None,also make sure you're using the latest GitHub version
@Vijayabhaskar96 thank you for your response! 

I used `git clone --depth=1 https://github.com/smurak/keras-preprocessing.git` to make sure to clone the last version but I got (0 images belonging to 2 classes.) bug.

However, I tried `git clone -b fix_found_0_images_bug https://github.com/smurak/keras-preprocessing.git` to clone the branch as you refer here, but I got
 `Cloning into 'keras-preprocessing'... fatal: Remote branch fix_found_0_images_bug not found in upstream  @origin`

**Comment by AlaaEzzeldin** [comment]
> you can create a dataframe which has absolute paths of all the images and it's respective classes,pass it to flow from dataframe and set the directory=None,also make sure you're using the latest GitHub version

I used git clone  `--depth=1 https://github.com/smurak/keras-preprocessing.git to make sure to clone the last version but I got (0 images belonging to 2 classes.) bug.`

However, I tried `git clone -b fix_found_0_images_bug https://github.com/smurak/keras-preprocessing.git `to clone the branch as referred here, but I got`
Cloning into 'keras-preprocessing'... fatal: Remote branch fix_found_0_images_bug not found in upstream @origin`

**Comment by AlaaEzzeldin** [comment]
sorry, but smth goes wrong, it still returns (0 images with 2 classes) !!

I'm using google colab, even if it Successfully installed Keras-Preprocessing-1.0.5, It seems that kernel still use the old version, as it gives me error when passing directory= None with` expected str, bytes or os.PathLike object, not NoneType`
also when passing drop_duplicates `flow_from_dataframe() got an unexpected keyword argument 'drop_duplicates'`, any suggestions?

**Comment by AlaaEzzeldin** [comment]
> No need to install from smurak's fork, the fix has been accepted, directly clone/install from this repository itself! `pip install git+https://github.com/keras-team/keras-preprocessing`

thank you, it works!

**Comment by rragundez** [comment]
this issue has been resolved and it should be closed @Dref360

**Comment by sumi89** [comment]
Hi, I installed keras 2.2.4 with the command "sudo pip install Keras==2.2.4". I am using absolute path in my dataframe, so I used directory = "None". But still it is showing "Found 0 images". What should I do?

**Comment by Vijayabhaskar96** [comment]
Make sure you have installed the latest keras_preprocessing available in github, and import from keras_preprocessing, not from keras.preprocessing. You can can refer this https://github.com/keras-team/keras-preprocessing/issues/116#issuecomment-452243221

**Comment by sumi89** [comment]
I installed the latest keras_preprocessing. Now I followed the way you refer. But still, the result is the same.

**Comment by Vijayabhaskar96** [comment]
Can you show me a sample of dataframe and the code? I can't say much until I see the problem.

**Comment by sumi89** [comment]
| filename | P>1 | P>5 | P>10 | P>30 | P>50 | P>100
-- | -- | -- | -- | -- | -- | -- | --
0 | /Volumes/New Volume/data/solar/hmi/2016/20160101_000000_M_1k.jpg | 1.012368649 | -0.692660009 | -0.870466716 | -1.120125969 | -1.216657295 | -1.47617678
1 | /Volumes/New Volume/data/solar/hmi/2016/20160101_001500_M_1k.jpg | 1.01508765 | -0.692622856 | -0.869243056 | -1.118829439 | -1.215764185 | -1.476253526
2 | /Volumes/New Volume/data/solar/hmi/2016/20160101_003000_M_1k.jpg | 1.017329202 | -0.686433035 | -0.858899834 | -1.096382579 | -1.19926382 | -1.46929793
3 | /Volumes/New Volume/data/solar/hmi/2016/20160101_004500_M_1k.jpg | 1.021744905 | -0.658922883 | -0.822584725 | -1.06169752 | -1.185955967 | -1.465233763
4 | /Volumes/New Volume/data/solar/hmi/2016/20160101_010000_M_1k.jpg | 1.027570602 | -0.613872785 | -0.763705944 | -1.025830681 | -1.174995583 | -1.462990272
5 | /Volumes/New Volume/data/solar/hmi/2016/20160101_011500_M_1k.jpg | 1.035636936 | -0.560119317 | -0.694757611 | -0.999555403 | -1.167191801 | -1.462942105

**Comment by sumi89** [comment]
pdf = pd.read_excel('images_and_target_log.xlsx')
datagen=ImageDataGenerator(rescale=1./255)
train_generator=datagen.flow_from_dataframe(dataframe=pdf1, directory = "None", color_mode= "grayscale" , 
                                            x_col="filename", y_col="P>100", class_mode="other", 
                                            target_size=input_shape[:2], batch_size=32)

**Comment by sumi89** [comment]
Sorry, in the third line it should be "dataframe=pdf".

**Comment by sumi89** [comment]
According to my understanding, I am using absolute path. I checked with the following two lines

path = pdf['filename'][0]
image.load_img(path, target_size=(224, 224))

And this shows me the image. That is why I am confident that I am using absolute path.

**Comment by sumi89** [comment]
Thanks for your time @Vijayabhaskar96  !

**Comment by Vijayabhaskar96** [comment]
The only suggestion I can give is, reinstall the keras_preprocessing from the GitHub repo as I suggested before and make sure you're using the one from keras_preprocessing. If you find the source of the problem please do inform here, if it's a bug I will look into it.

**Comment by sumi89** [comment]
I will. Thanks again :)

**Comment by sumi89** [comment]
I needed to restart my Spyder environment. Now it works :) I really appreciate your help @Vijayabhaskar96 :)

**Comment by SmartManoj** [comment]
> No need to install from smurak's fork, the fix has been accepted, directly clone/install from this repository itself! `pip install git+https://github.com/keras-team/keras-preprocessing`

Did it move to pypi?
