### ISSUE TITLE
[API DESIGN REVIEW] Add random crop support to ImageDataGenerator 

### ISSUE THREAD

**Issue by datumbox** [keras-team/keras-preprocessing#69]
Modify the `ImageDataGenerator` class to receive an extra boolean `target_size` argument on its constructor and update its methods to produce random crops during training.

See Keras API Design Review at https://docs.google.com/document/d/1zdSsPCxbrCedQgOYqc-Ne6gWzYqIqIqDgExHyThxl1o/edit?usp=sharing

See Keras Issue https://github.com/keras-team/keras/issues/11237 for more details.

**Comment by Dref360** [comment]
This seems like a reasonable addition.

What would happen if the loaded images are smaller than the required crop-size? Are we just gonna pad with 0?

**Comment by Dref360** [comment]
Stretching seems okay, it should be in the documentation.

Please submit a PR
