### ISSUE TITLE
Installation issues with keras-preprocessing to get flow_from_dataframe

### ISSUE THREAD

**Issue by zishanahmed08** [keras-team/keras-preprocessing#94]
Could you please tell me the right procedure of installation.Since the feature flow_from_dataframe is not availble in the pip version, i try to get it installed from the gitub repo. This is what i tried and failed in my virtual environment 

```
pip uninstall keras
pip uninstall keras-preprocessing
pip install git+https://github.com/keras-team/keras-preprocessing.git
pip install keras
````

What am i doing wrong here?

**Comment by Vijayabhaskar96** [comment]
Try:
```
pip install keras
pip uninstall keras-preprocessing
pip install git+https://github.com/keras-team/keras-preprocessing.git

```

**Comment by zishanahmed08** [comment]
It did not work out for me this way. I finally resorted to importing it with from `keras_preprocessing.image import ImageDataGenerator` instead of `from keras.preprocessing.image import ImageDataGenerator`
